/**
 * @author Thabang Mamoloko
 */
package Classes;

import java.security.*;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;

/**
 * 
 */
public class LoginController {
	private String email;
	private String password;
	/**
	 * @param email
	 * @param password
	 */
	public LoginController(String email, String password) {
		this.email = email;
		this.password = password;
	}
	
	/**
	 * @return true if the email/password matched a dealer record, false
	 *         otherwise (wrong password, unknown email, or a DB error -
	 *         an alert is shown to the user in every failure case).
	 */
	public boolean loginUser() {
		String sql = "SELECT pwd FROM dealers WHERE dealer_email = ?;";
		//Dbh dbh = new Dbh();
		try {
			Connection conn = Dbh.getConnection();
			PreparedStatement stmt = conn.prepareStatement(sql);
			stmt.setString(1, this.email);
			
			ResultSet result = stmt.executeQuery();
			if(result.next()) {
				String enteredHash = hashPassword(password);
				String userPwd = result.getString("pwd");
				if(enteredHash.equals(userPwd)) {
					return true;
				}else {
					showInfoAlert("Wrong Password!");
					return false;
				}
			}else {
				showInfoAlert("User not found!");
				return false;
			}
			
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			showInfoAlert("Something went wrong - please try again.");
			return false;
		}
	}
	
	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}
	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
	
	
	// Helper functions
	private void showInfoAlert(String message) {
        Alert alert = new Alert(AlertType.INFORMATION, message);
        alert.setHeaderText(null);
        alert.showAndWait();
    }
	// Password hashing - Generated by co-pilot
    private static String hashPassword(String password) {
    	try {
    		MessageDigest md = MessageDigest.getInstance("SHA-256");
    		byte[] hash = md.digest(password.getBytes());
    		
    		StringBuilder hexString = new StringBuilder();
    		
    		for(byte b : hash) {
    			String hex = Integer.toHexString(0xff & b);
    			
    			if(hex.length() == 1) {
    				hexString.append('0');
    			}
    			
    			hexString.append(hex);
    		}
    		return hexString.toString();
    	}catch(NoSuchAlgorithmException e) {
    		throw new RuntimeException(e);
    	}
    	
    }
	
}